name: Build
on:
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.query.outputs.linux }}
      u-boot: ${{ steps.query.outputs.u-boot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "linux=$(./bsp json profile linux)" >> $GITHUB_OUTPUT
          echo "u-boot=$(./bsp json profile u-boot)" >> $GITHUB_OUTPUT
  # build_u-boot:
  #   needs: query
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       targets: [ u-boot ]
  #       profiles: ${{fromJSON(needs.query.outputs.u-boot)}}
  #   steps:
  #     - name: Build
  #       uses: radxa-repo/bsp@main
  #       with:
  #         target: ${{ matrix.targets }}
  #         edition: ${{ matrix.profiles }}
  #         artifacts: true
  build_linux:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [linux]
        profiles: [rk2312]
    steps:
      - name: Build
        uses: iris-vision/bsp@main
        with:
          target: ${{ matrix.targets }}
          edition: ${{ matrix.profiles }}
          artifacts: true
